function A = testmatrix(x,y,theta)
%TESTMATRIX
%    A = TESTMATRIX(X,Y,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Sep-2018 10:20:33

A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,cos(theta),-sin(theta),0.0],[3,3]);
